export const LANGS = [
  { id: 'en', name: 'English', flag: '🇬🇧' },
  { id: 'fr', name: 'French', flag: '🇫🇷' },
  { id: 'it', name: 'Italian', flag: '🇮🇹' },
  { id: 'es', name: 'Spanish', flag: '🇪🇸' },
  { id: 'pt', name: 'Portuguese', flag: '🇵🇹' },
  { id: 'ru', name: 'Russian', flag: '🇷🇺' },
  { id: 'zh', name: 'Chinese', flag: '🇨🇳' },
  { id: 'ja', name: 'Japanese', flag: '🇯🇵' },
] as const

export type Lang = (typeof LANGS)[number]['id']

const en = {
  info: 'Information',
  brochure: 'Brochure',
  specs: 'Specs',
  charter: 'Charter',
  contact: 'Contact',
  language: 'Language',
  themeDark: 'Dark',
  themeLight: 'Light',
  openMenu: 'Open menu',
  closeMenu: 'Close menu',
  theBoat: 'The boat',
  privacy: 'Privacy',
  crew: 'Crew',
  crewLogin: 'Crew login',
  onThisSite: 'On this site',
  footBlurb: 'Built in Cape Town. Mediterranean summer. Caribbean winter.',
  madeForWind: 'Made for the wind.',
  builtForSea: 'Built for the sea.',
  sw110: 'Southern Wind 110',
  sailingYacht: 'Sailing Yacht',
  capeTown: 'Cape Town, South Africa',
  medCruise: 'Mediterranean & Caribbean',
  explore: 'Explore',
  specifications: 'Specifications',
  youtube: 'YouTube',
  copyYear: '© 2026 Thalima',
  cookieBody:
    'We use a single cookie to remember this choice. Nothing else is tracked unless you accept.',
  cookieAccept: 'Accept',
  cookieEssential: 'Essential only',
  introTitle1: 'A Southern Wind 110.',
  introTitle2: 'One quiet week in the Med.',
  introBody:
    'Built in Cape Town, drawn by Farr, dressed by Nauta. We take a short list of weeks — Italy, Sardinia, the South of France — and the same five who sail her. Charter, crew, the boat. Under one roof, without the handoffs.',
  introP1:
    'She is the only 110-footer Southern Wind has ever built. Farr Yacht Design drew her lines, Nauta Design shaped her form, and craftsmen in Cape Town built her. The result is 33.65 metres of flush-decked carbon composite that sails like a thoroughbred and cruises with the calm of a private villa at sea.',
  introP2:
    'At the helm, she answers to a light touch. At anchor, she offers space and quiet. Her wide teak decks open onto sunbeds and a shaded cockpit where long lunches can easily run into sunset. A hydraulic swim platform lowers you into clear water. A private crew cockpit aft means the work of sailing never intrudes on your time on board.',
  introP3:
    'Below, a complete renovation completed in 2024 has given her a new interior of pale, bleached teak, crème linen, brushed metal and soft natural light. Four en-suite cabins, a full-beam Owner’s suite, and a saloon made for gathering together all share one simple idea: that luxury should feel effortless.',
  introP4:
    'Five dedicated crew look after her and her guests: Captain, Mate, Engineer, Stewardess and Chef. Her seasons follow the sun, from the Mediterranean in summer to the Caribbean in winter.',
  introClose: 'Thalima. Where performance meets peace.',

  storyEye: 'Her Story',
  storyTitle: 'A legend from the southern tip of Africa',
  storyP1:
    'Thalima was born in Cape Town in 2010, at the shipyard that built its name on one principle: a great yacht should be exhilarating to sail and a pleasure to live aboard.',
  storyP2:
    'Three names shaped her. Southern Wind built her with uncompromising care. Farr Yacht Design, the naval architects behind some of the fastest yachts on the ocean, designed her hull. Nauta Design gave her the clean, elegant lines that turn heads in every harbour. Beneath the surface she is pure engineering: an epoxy-infused hull of Kevlar and carbon, a carbon deck and pilothouse, and a soaring four-spreader Nordic carbon mast carrying 566 square metres of sail.',
  storyP3:
    'Her owners have cared for her with rare devotion. Her mast and rigging were fully restored in 2022. Between 2023 and 2024 she spent a year in refit, where she was reimagined from the inside out. She received a new interior, new generators, a full suite of B&G navigation electronics, new canvas, and a new mainsail and staysail by Incidence. In 2026 she was dressed in fresh Ontario Blue.',
  storyP4: 'More than fifteen years after her launch, Thalima is not simply well kept. She is at her finest.',
  watersEye: 'Her Waters',
  watersTitle: 'Two seas. Endless summer.',
  medTitle: 'The Mediterranean',
  medBody:
    'When the season begins, Thalima makes the Mediterranean her playground. You might wake in a hidden Balearic cove, lunch beneath the cliffs of Corsica, sail across to Sardinia’s emerald coast, and arrive in the Riviera’s most glamorous harbours by evening. She is swift enough to cover real distance between anchorages and agile enough to reach the places larger yachts cannot.',
  caribTitle: 'The Caribbean',
  caribBody:
    'As autumn arrives, she crosses the Atlantic for the Caribbean. Here the trade winds are steady and warm and the water is endlessly turquoise. Island by island, from powder-white beaches to quiet reef-sheltered anchorages, the Caribbean shows why Thalima was built. This is sailing at its purest.',
  watersNote:
    'With generous range, Thalima travels far and stays comfortably self-sufficient. Every itinerary is designed around you, whether that means long, spirited days under sail or slow, golden afternoons with nowhere to be.',
  charterBlockEye: 'Charter Thalima',
  charterBlockTitle: 'Your yacht. Your rhythm. Your crew.',
  charterBlockLead:
    'A charter aboard Thalima is personal. Her crew of five are a close team: Captain, Mate, Engineer, Stewardess and Chef. They know the yacht intimately and look after every guest with warm, unobtrusive care. Afterwards, guests often say it felt less like a charter and more like being welcomed into a private home at sea.',
  lifeTitle: 'Life aboard',
  lifeBody:
    'Four en-suite cabins suit families and friends. The Owner’s suite has a private study, walk-through dressing room and Corian rain shower. The VIP cabin has a walkaround double berth, and the two twin cabins each have a pullman berth. The light-filled saloon and TV lounge are ideal for quiet evenings, and the centre cockpit becomes an open-air dining room under the stars.',
  tableTitle: 'At the table',
  tableBody:
    'The Chef cooks around the day’s catch, the local markets and your preferences. Breakfast might be on deck, lunch at anchor, and dinner by candlelight in the cockpit. Every menu is created for you.',
  playTitle: 'At play',
  playBody:
    'When the anchor drops, the sea is yours to explore. Take out the Williams SportJet tender, try wing-foiling, waterskiing or wakeboarding (with personal coaching for beginners), glide out on a paddleboard or kayak, or snorkel the reefs. Guests who love to sail are welcome at the wheel. Those who would rather simply watch the sails fill and the coastline drift by are equally welcome.',
  charterEnquire: 'Charter enquiries are welcome through Roccabella Yachts.',
  manageEye: 'Management',
  manageTitle: 'Care behind every detail',
  manageP1:
    'Thalima is managed by Roccabella Yachts, a respected name in luxury yacht charter, sales and management.',
  manageP2:
    'Roccabella works with a small, highly experienced team by design. This allows them to give each yacht close, personal attention. For Thalima, that means expert technical oversight, a crew with full support, and an operation run to the highest standard, so every charter runs smoothly and every guest arrives to a yacht in perfect condition.',
  interiorEye: 'Interior',
  interiorTitle: 'Pale teak. Soft light. Effortless.',
  interiorLead:
    'The 2024 refit: Owner’s suite, twin cabins, galley, saloon and every detail in between.',
  servicesEye: 'Aboard',
  servicesTitle: 'The yacht, and the week you take her.',
  svc1Title: 'A week you’ll actually remember.',
  svc1Body:
    'Tell us when, and where. We put you on Thalima with the crew that lives aboard — Mediterranean in summer, Caribbean in winter, dinner when the light goes.',
  svc1Cta: 'Start a charter',
  svc2Title: 'As she is today.',
  svc2Body:
    'Deck and interior after the 2024 refit. Owner’s suite, four en-suite cabins, the cockpit when the light goes.',
  svc2Cta: 'See the boat',
  svc3Title: 'Brochure and spec.',
  svc3Body:
    'Deck, interior, the lines. The full specification if you want numbers. Both open as PDFs.',
  svc3Cta: 'Open the brochure',
  banner: 'Where performance meets peace.',
  onboard: 'On board',
  selectTitle1: 'A small selection, current today.',
  selectTitle2: 'The rest is below deck.',
  paper: 'On paper',
  worth: 'Worth reading',
  journalLead: 'The brochure, the spec, or a week that is still open.',
  readMore: 'Read more',
  writeToUs: 'Write to us',
  postBrochure: 'Brochure',
  postBrochureTitle: 'Deck, interior, the lines.',
  postSpec: 'Specification',
  postSpecTitle: '33.65 m, Farr, Nauta, Ontario Blue.',
  postCharterTitle: 'Tell us the week. We come back with a coast.',
  ownerSuite: 'Owner suite',
  ownerSuiteB: 'Full-beam, private study',
  ownerSuiteP: 'Ensuite · 2024 refit',
  underSail: 'Under sail',
  underSailB: 'Thoroughbred on a light touch',
  underSailP: '33.65 m · 8 guests',
  evening: 'Evening',
  eveningB: 'Dinner under the stars',
  eveningP: 'Centre cockpit',
  lounge: 'Lounge',
  loungeB: 'Quiet evenings below',
  loungeP: 'Interior',
  saloon: 'Saloon',
  saloonB: 'Made for gathering',
  saloonP: 'Nauta · bleached teak',
  contactTitle: 'Write, or call.',
  contactLead: 'Charter enquiries are welcome through Roccabella Yachts.',
  telephone: 'Telephone',
  sendEnquiry: 'Send an enquiry',
  onDeck: 'On deck and below',
  coveAlt: 'A granite cove in the Mediterranean',
  charterTitle: 'Your yacht. Your rhythm. Your crew.',
  charterLead:
    'A charter aboard Thalima is personal. Eight guests, five crew, Mediterranean summer and Caribbean winter. Enquiries through Roccabella Yachts.',
  theWeek: 'The week',
  lowSeason: 'Low season',
  highSeason: 'High season',
  guests: 'Guests',
  crewN: 'Crew',
  summer: 'Summer',
  tender: 'Tender',
  weekNote:
    'Mediterranean or Caribbean — every itinerary is designed around you. Terms are MYBA. Enquiries go through Roccabella Yachts.',
  enquire: 'Enquire',
  enquireLead: 'Tell us the week. Roccabella reads it and comes back to you.',
  formOk: 'Your mail app should open with the enquiry. If it doesn’t, write to',
  formNext: 'Continue',
  formBack: 'Back',
  formThanks: 'The team will get back to you within 24 hours.',
  firstName: 'First name *',
  lastName: 'Last name',
  email: 'Email address *',
  phone: 'Phone number',
  startDate: 'Preferred start date',
  endDate: 'Preferred end date',
  guestCount: 'Number of guests',
  lengthInterest: 'Length of interest',
  location: 'Preferred location',
  message: 'Your message',
  formNote: 'These details are needed to reply. You can ask us to forget them at any time.',
  consent: 'I agree that Roccabella Yachts may use these details to reply to this charter enquiry.',
  send: 'Send enquiry',
  g6: 'Up to 6 guests',
  g8: '6 – 8 guests',
  gMore: 'More than 8 guests',
  mediterranean: 'Mediterranean',
  nEurope: 'Northern Europe',
  caribbean: 'Caribbean',
  asiaPacific: 'Asia-Pacific',
  other: 'Other',
  boatTitle: 'Southern Wind 110 RS',
  boatLead:
    'The only 110-footer Southern Wind has ever built. Farr hull, Nauta form, Cape Town craft. Eight guests, five crew. Reimagined inside out in 2024.',
  deck: 'Deck',
  deck1:
    'Wide teak decks open onto sunbeds and a shaded cockpit where long lunches run into sunset. A hydraulic swim platform lowers you into clear water. Crew work from a private cockpit aft — sailing never intrudes on your time aboard.',
  deck2: 'The Williams SportJet sits ready when the anchor drops. Guests who love to sail are welcome at the wheel.',
  interior: 'Interior',
  interior1:
    'Pale, bleached teak, crème linen, brushed metal and soft natural light. Owner’s suite with private study and Corian rain shower, VIP with a walkaround double, two twins with pullman berths. Saloon and TV lounge for quiet evenings.',
  brochureTitle: 'The brochure.',
  brochureLead: 'Deck, interior, the lines. Opens as a PDF.',
  openBrochure: 'Open the brochure',
  specsTitle: 'The numbers.',
  specsLead: 'The full specification if you want the sheet. The short list is here.',
  openSpec: 'Open the spec PDF',
  privacyTitle: 'What we keep.',
  privacy1:
    'A charter enquiry is sent from your mail app. We don’t store the form on this site.',
  privacy2:
    'The cookie banner writes one value in your browser — accept or essential — so we don’t ask again. There is no analytics pixel, no ad network, and no third-party tracker on these pages.',
  privacy3: 'Crew login is a separate app. Photographs and names of the crew stay off the public site.',
}

export type SiteCopy = typeof en

export const copy: Record<Lang, SiteCopy> = {
  en,
  fr: {
    ...en,
    info: 'Information',
    brochure: 'Brochure',
    specs: 'Spécifications',
    charter: 'Charter',
    contact: 'Contact',
    language: 'Langue',
    themeDark: 'Sombre',
    themeLight: 'Clair',
    openMenu: 'Ouvrir le menu',
    closeMenu: 'Fermer le menu',
    theBoat: 'Le bateau',
    privacy: 'Confidentialité',
    crew: 'Équipage',
    crewLogin: 'Connexion équipage',
    onThisSite: 'Sur ce site',
    footBlurb: 'Construit au Cap. Navigué en Méditerranée.',
    madeForWind: 'Faite pour le vent.',
    builtForSea: 'Bâtie pour la mer.',
    sailingYacht: 'Yacht à voile',
    capeTown: 'Le Cap, Afrique du Sud',
    medCruise: 'Croisière en Méditerranée',
    explore: 'Explorer',
    specifications: 'Spécifications',
    cookieBody:
      'Un seul cookie mémorise ce choix. Rien d’autre n’est suivi, sauf si vous acceptez.',
    cookieAccept: 'Accepter',
    cookieEssential: 'Essentiel seulement',
    introTitle1: 'Un Southern Wind 110.',
    introTitle2: 'Une semaine calme en Méditerranée.',
    introBody:
      'Construit au Cap, dessiné par Farr, habillé par Nauta. Une courte liste de semaines — Italie, Sardaigne, Côte d’Azur — et les cinq qui vivent à bord. Charter, équipage, le bateau. Sous un même toit, sans intermédiaire.',
    servicesEye: 'À bord',
    servicesTitle: 'Le bateau, et la semaine que vous prenez.',
    svc1Title: 'Une semaine dont on se souvient.',
    svc1Body:
      'Dites-nous quand, et où. Nous vous mettons sur Thalima avec l’équipage qui vit à bord — Méditerranée l’été, le Williams sur le pont avant, dîner quand la lumière baisse.',
    svc1Cta: 'Commencer un charter',
    svc2Title: 'Telle qu’elle est aujourd’hui.',
    svc2Body:
      'Pont et intérieur après la refonte 2024. Suite propriétaire à l’avant, carré pour dix, le cockpit quand la lumière baisse.',
    svc2Cta: 'Voir le bateau',
    svc3Title: 'Brochure et spécifications.',
    svc3Body:
      'Novembre 2025 : pont, intérieur, les lignes. La spec de juillet pour les chiffres. Les deux s’ouvrent en PDF.',
    svc3Cta: 'Ouvrir la brochure',
    banner: 'La bonne semaine change\nla façon dont le temps passe.',
    onboard: 'À bord',
    selectTitle1: 'Une petite sélection, actuelle.',
    selectTitle2: 'Le reste est dans la brochure.',
    paper: 'Sur papier',
    worth: 'À lire',
    journalLead: 'La brochure, la spec, ou une semaine encore libre.',
    readMore: 'Lire',
    writeToUs: 'Écrire',
    postBrochure: 'Brochure · nov. 2025',
    postBrochureTitle: 'Pont, intérieur, les lignes.',
    postSpec: 'Spécification',
    postSpecTitle: '33,65 m, Farr, Nauta, Ontario Blue.',
    postCharterTitle: 'Dites-nous la semaine. Nous revenons avec une côte.',
    ownerSuite: 'Suite propriétaire',
    ownerSuiteB: 'Avant, couchette walk-around',
    ownerSuiteP: 'Salle de bain · refonte 2024',
    underSail: 'Sous voile',
    underSailB: 'Onze nœuds quand c’est gentil',
    underSailP: '33,65 m · 8 hôtes',
    evening: 'Soir',
    eveningB: 'Dix autour de la table',
    eveningP: 'Cockpit central',
    lounge: 'Salon',
    loungeB: 'Après l’hiver à Badalona',
    loungeP: 'Intérieur',
    saloon: 'Carré',
    saloonB: 'Dix places, sans bruit',
    saloonP: 'Nauta · teck',
    contactTitle: 'Écrire, ou appeler.',
    contactLead: 'Le charter va au propriétaire. Direct — sans courtier.',
    telephone: 'Téléphone',
    sendEnquiry: 'Envoyer une demande',
    onDeck: 'Sur le pont et en bas',
    coveAlt: 'Une calanque de granite en Sardaigne',
    charterTitle: 'Une semaine sur Thalima.',
    charterLead:
      'Southern Wind 110 RS. Huit hôtes, cinq d’équipage, été méditerranéen. Conditions MYBA — nous revenons avec la côte une fois la semaine connue.',
    theWeek: 'La semaine',
    lowSeason: 'Basse saison',
    highSeason: 'Haute saison',
    guests: 'Hôtes',
    crewN: 'Équipage',
    summer: 'Été',
    tender: 'Annexe',
    weekNote: 'Italie, Sardaigne, Côte d’Azur. Conditions MYBA. La demande va au propriétaire.',
    enquire: 'Demande',
    enquireLead: 'Dites-nous la semaine. Le propriétaire la lit et vous répond.',
    formOk: 'Votre messagerie devrait s’ouvrir avec la demande. Sinon, écrivez à',
    formNext: 'Continuer',
    formBack: 'Retour',
    formThanks: 'L’équipe vous répondra sous 24 heures.',
    firstName: 'Prénom *',
    lastName: 'Nom',
    email: 'Adresse e-mail *',
    phone: 'Téléphone',
    startDate: 'Date de début',
    endDate: 'Date de fin',
    guestCount: 'Nombre d’hôtes',
    lengthInterest: 'Longueur souhaitée',
    location: 'Zone souhaitée',
    message: 'Votre message',
    formNote: 'Le propriétaire a besoin de ces détails pour répondre. Vous pouvez demander leur oubli à tout moment.',
    consent: 'J’accepte que le propriétaire de Thalima utilise ces informations pour répondre à cette demande de charter.',
    send: 'Envoyer la demande',
    g6: 'Jusqu’à 6 hôtes',
    g8: '6 – 8 hôtes',
    gMore: 'Plus de 8 hôtes',
    mediterranean: 'Méditerranée',
    nEurope: 'Europe du Nord',
    caribbean: 'Caraïbes',
    asiaPacific: 'Asie-Pacifique',
    other: 'Autre',
    boatTitle: 'Southern Wind 110 RS',
    boatLead:
      '33,65 mètres. Coque Farr, intérieur Nauta, construit au Cap. Huit hôtes, cinq d’équipage. Les espaces hôtes ont été refaits à Badalona, hiver 2024.',
    deck: 'Pont',
    deck1:
      'Cockpit hôtes et bains de soleil ensemble. Dodger, bimini, et un taud de bôme quand la lumière est dure. L’équipage travaille le cockpit arrière — il ne traverse pas les hôtes pour descendre.',
    deck2: 'La plateforme de bain est l’accès à l’eau. Le Williams est sur le pont avant.',
    interior: 'Intérieur',
    interior1:
      'Propriétaire à l’avant : couchette walk-around, bureau, dressing, salle de bain. VIP avec king, deux lits jumeaux à l’arrière convertibles. Le carré assied dix. Équipage et hôtes n’ont pas la même descente.',
    brochureTitle: 'La brochure.',
    brochureLead: 'Novembre 2025. Pont, intérieur, les lignes. S’ouvre en PDF.',
    openBrochure: 'Ouvrir la brochure',
    specsTitle: 'Les chiffres.',
    specsLead: 'La spec de juillet pour la feuille complète. La liste courte est ici.',
    openSpec: 'Ouvrir le PDF spec',
    privacyTitle: 'Ce que nous gardons.',
    privacy1:
      'Une demande de charter part de votre messagerie vers le propriétaire. Nous ne stockons pas le formulaire sur ce site.',
    privacy2:
      'La bannière cookies écrit une valeur dans votre navigateur — accepter ou essentiel — pour ne plus demander. Pas de pixel analytics, pas de publicité, pas de tracker tiers.',
    privacy3: 'La connexion équipage est une autre application. Photos et noms d’équipage restent hors du site public.',
  },
  it: {
    ...en,
    info: 'Informazioni',
    brochure: 'Brochure',
    specs: 'Specifiche',
    charter: 'Charter',
    contact: 'Contatti',
    language: 'Lingua',
    themeDark: 'Scuro',
    themeLight: 'Chiaro',
    openMenu: 'Apri il menu',
    closeMenu: 'Chiudi il menu',
    theBoat: 'La barca',
    privacy: 'Privacy',
    crew: 'Equipaggio',
    crewLogin: 'Accesso equipaggio',
    onThisSite: 'Su questo sito',
    footBlurb: 'Costruita a Città del Capo. Navigata in Mediterraneo.',
    madeForWind: 'Fatta per il vento.',
    builtForSea: 'Costruita per il mare.',
    sailingYacht: 'Yacht a vela',
    capeTown: 'Città del Capo, Sudafrica',
    medCruise: 'Crociera in Mediterraneo',
    explore: 'Esplora',
    specifications: 'Specifiche',
    cookieBody:
      'Un solo cookie ricorda questa scelta. Nient’altro viene tracciato, salvo consenso.',
    cookieAccept: 'Accetta',
    cookieEssential: 'Solo essenziali',
    introTitle1: 'Un Southern Wind 110.',
    introTitle2: 'Una settimana quieta in Mediterraneo.',
    introBody:
      'Costruita a Città del Capo, disegnata da Farr, vestita da Nauta. Poche settimane — Italia, Sardegna, Costa Azzurra — e gli stessi cinque che vivono a bordo. Charter, equipaggio, la barca. Sotto lo stesso tetto, senza intermediari.',
    servicesEye: 'A bordo',
    servicesTitle: 'La barca, e la settimana che prendete.',
    svc1Title: 'Una settimana che si ricorda.',
    svc1Body:
      'Diteci quando, e dove. Vi mettiamo su Thalima con l’equipaggio che vive a bordo — Mediterraneo d’estate, il Williams a prua, cena quando scende la luce.',
    svc1Cta: 'Inizia un charter',
    svc2Title: 'Com’è oggi.',
    svc2Body:
      'Ponte e interni dopo il refit 2024. Suite armatore a prua, salone per dieci, il pozzetto quando scende la luce.',
    svc2Cta: 'Vedi la barca',
    svc3Title: 'Brochure e specifiche.',
    svc3Body:
      'Novembre 2025: ponte, interni, le linee. La spec di luglio per i numeri. Entrambe in PDF.',
    svc3Cta: 'Apri la brochure',
    banner: 'La settimana giusta cambia\nil modo in cui passa il tempo.',
    onboard: 'A bordo',
    selectTitle1: 'Una piccola selezione, attuale.',
    selectTitle2: 'Il resto è nella brochure.',
    paper: 'Su carta',
    worth: 'Da leggere',
    journalLead: 'La brochure, la spec, o una settimana ancora libera.',
    readMore: 'Leggi',
    writeToUs: 'Scrivici',
    postBrochure: 'Brochure · nov 2025',
    postBrochureTitle: 'Ponte, interni, le linee.',
    postSpec: 'Specifiche',
    postSpecTitle: '33,65 m, Farr, Nauta, Ontario Blue.',
    postCharterTitle: 'Diteci la settimana. Torniamo con una costa.',
    ownerSuite: 'Suite armatore',
    ownerSuiteB: 'A prua, letto walk-around',
    ownerSuiteP: 'Bagno · refit 2024',
    underSail: 'A vela',
    underSailB: 'Undici nodi quando è clemente',
    underSailP: '33,65 m · 8 ospiti',
    evening: 'Sera',
    eveningB: 'Dieci a tavola',
    eveningP: 'Pozzetto centrale',
    lounge: 'Lounge',
    loungeB: 'Dopo l’inverno a Badalona',
    loungeP: 'Interni',
    saloon: 'Salone',
    saloonB: 'Dieci posti, in silenzio',
    saloonP: 'Nauta · teak',
    contactTitle: 'Scrivere, o chiamare.',
    contactLead: 'Il charter va all’armatore. Diretto — senza broker.',
    telephone: 'Telefono',
    sendEnquiry: 'Invia una richiesta',
    onDeck: 'In coperta e sotto',
    coveAlt: 'Una cala di granito in Sardegna',
    charterTitle: 'Una settimana su Thalima.',
    charterLead:
      'Southern Wind 110 RS. Otto ospiti, cinque di equipaggio, estate mediterranea. Termini MYBA — torniamo con la costa quando abbiamo la settimana.',
    theWeek: 'La settimana',
    lowSeason: 'Bassa stagione',
    highSeason: 'Alta stagione',
    guests: 'Ospiti',
    crewN: 'Equipaggio',
    summer: 'Estate',
    tender: 'Tender',
    weekNote: 'Italia, Sardegna, Costa Azzurra. Termini MYBA. La richiesta va all’armatore.',
    enquire: 'Richiesta',
    enquireLead: 'Diteci la settimana. L’armatore la legge e vi risponde.',
    formOk: 'Dovrebbe aprirsi la mail con la richiesta. Se no, scrivete a',
    formNext: 'Continua',
    formBack: 'Indietro',
    formThanks: 'Il team vi risponderà entro 24 ore.',
    firstName: 'Nome *',
    lastName: 'Cognome',
    email: 'Email *',
    phone: 'Telefono',
    startDate: 'Data di inizio',
    endDate: 'Data di fine',
    guestCount: 'Numero di ospiti',
    lengthInterest: 'Lunghezza di interesse',
    location: 'Zona preferita',
    message: 'Il vostro messaggio',
    formNote: 'L’armatore ha bisogno di questi dati per rispondere. Potete chiederne la cancellazione in qualsiasi momento.',
    consent: 'Accetto che l’armatore di Thalima usi questi dati per rispondere a questa richiesta di charter.',
    send: 'Invia richiesta',
    g6: 'Fino a 6 ospiti',
    g8: '6 – 8 ospiti',
    gMore: 'Più di 8 ospiti',
    mediterranean: 'Mediterraneo',
    nEurope: 'Europa del Nord',
    caribbean: 'Caraibi',
    asiaPacific: 'Asia-Pacifico',
    other: 'Altro',
    boatLead:
      '33,65 metri. Scafo Farr, interni Nauta, costruita a Città del Capo. Otto ospiti, cinque di equipaggio. Gli spazi ospiti rifatti a Badalona, inverno 2024.',
    deck: 'Ponte',
    deck1:
      'Pozzetto ospiti e sunpad insieme. Dodger, bimini, e un tendalino del boma quando la luce è dura. L’equipaggio lavora il pozzetto di poppa — non attraversa gli ospiti per scendere.',
    deck2: 'La piattaforma di bagno è l’accesso all’acqua. Il Williams sta a prua.',
    interior: 'Interni',
    interior1:
      'Armatore a prua: letto walk-around, studio, cabina armadio, bagno. VIP con king, due letti singoli a poppa unibili. Il salone siede dieci. Equipaggio e ospiti non condividono la discesa.',
    brochureTitle: 'La brochure.',
    brochureLead: 'Novembre 2025. Ponte, interni, le linee. Si apre in PDF.',
    openBrochure: 'Apri la brochure',
    specsTitle: 'I numeri.',
    specsLead: 'La spec di luglio per il foglio completo. La lista breve è qui.',
    openSpec: 'Apri il PDF spec',
    privacyTitle: 'Cosa teniamo.',
    privacy1:
      'Una richiesta di charter parte dalla vostra mail verso l’armatore. Non memorizziamo il modulo su questo sito.',
    privacy2:
      'Il banner cookie scrive un valore nel browser — accetta o essenziale — per non chiedere di nuovo. Nessun pixel, nessuna pubblicità, nessun tracker di terzi.',
    privacy3: 'Il login equipaggio è un’altra app. Foto e nomi restano fuori dal sito pubblico.',
  },
  es: {
    ...en,
    info: 'Información',
    brochure: 'Folleto',
    specs: 'Especificaciones',
    charter: 'Chárter',
    contact: 'Contacto',
    language: 'Idioma',
    themeDark: 'Oscuro',
    themeLight: 'Claro',
    openMenu: 'Abrir menú',
    closeMenu: 'Cerrar menú',
    theBoat: 'El barco',
    privacy: 'Privacidad',
    crew: 'Tripulación',
    crewLogin: 'Acceso tripulación',
    onThisSite: 'En este sitio',
    footBlurb: 'Construido en Ciudad del Cabo. Navegado en el Mediterráneo.',
    madeForWind: 'Hecha para el viento.',
    builtForSea: 'Construida para el mar.',
    sailingYacht: 'Yate de vela',
    capeTown: 'Ciudad del Cabo, Sudáfrica',
    medCruise: 'Crucero en el Mediterráneo',
    explore: 'Explorar',
    specifications: 'Especificaciones',
    cookieBody:
      'Una sola cookie recuerda esta elección. Nada más se rastrea salvo que acepte.',
    cookieAccept: 'Aceptar',
    cookieEssential: 'Solo esenciales',
    introTitle1: 'Un Southern Wind 110.',
    introTitle2: 'Una semana quieta en el Mediterráneo.',
    introBody:
      'Construido en Ciudad del Cabo, dibujado por Farr, vestido por Nauta. Una lista corta de semanas — Italia, Cerdeña, el sur de Francia — y los mismos cinco que viven a bordo. Chárter, tripulación, el barco. Bajo un mismo techo, sin intermediarios.',
    servicesEye: 'A bordo',
    servicesTitle: 'El barco, y la semana que toma.',
    svc1Title: 'Una semana que se recuerda.',
    svc1Body:
      'Díganos cuándo, y dónde. Le ponemos en Thalima con la tripulación que vive a bordo — Mediterráneo en verano, el Williams a proa, cena cuando baja la luz.',
    svc1Cta: 'Empezar un chárter',
    svc2Title: 'Como está hoy.',
    svc2Body:
      'Cubierta e interior tras el refit 2024. Suite del armador a proa, salón para diez, el cockpit cuando baja la luz.',
    svc2Cta: 'Ver el barco',
    svc3Title: 'Folleto y especificaciones.',
    svc3Body:
      'Noviembre 2025: cubierta, interior, las líneas. La spec de julio para los números. Ambos se abren en PDF.',
    svc3Cta: 'Abrir el folleto',
    banner: 'La semana justa cambia\ncómo pasa el tiempo.',
    onboard: 'A bordo',
    selectTitle1: 'Una pequeña selección, actual.',
    selectTitle2: 'El resto está en el folleto.',
    paper: 'En papel',
    worth: 'Para leer',
    journalLead: 'El folleto, la spec, o una semana aún libre.',
    readMore: 'Leer',
    writeToUs: 'Escríbanos',
    postBrochure: 'Folleto · nov 2025',
    postBrochureTitle: 'Cubierta, interior, las líneas.',
    postSpec: 'Especificación',
    postSpecTitle: '33,65 m, Farr, Nauta, Ontario Blue.',
    postCharterTitle: 'Díganos la semana. Volvemos con una costa.',
    ownerSuite: 'Suite del armador',
    ownerSuiteB: 'A proa, cama walk-around',
    ownerSuiteP: 'Baño · refit 2024',
    underSail: 'A vela',
    underSailB: 'Once nudos cuando es amable',
    underSailP: '33,65 m · 8 huéspedes',
    evening: 'Atardecer',
    eveningB: 'Diez en la mesa',
    eveningP: 'Cockpit central',
    lounge: 'Salón',
    loungeB: 'Después del invierno en Badalona',
    loungeP: 'Interior',
    saloon: 'Salón',
    saloonB: 'Diez asientos, en silencio',
    saloonP: 'Nauta · teca',
    contactTitle: 'Escribir, o llamar.',
    contactLead: 'El chárter va al armador. Directo — sin broker.',
    telephone: 'Teléfono',
    sendEnquiry: 'Enviar una consulta',
    onDeck: 'En cubierta y abajo',
    coveAlt: 'Una cala de granito en Cerdeña',
    charterTitle: 'Una semana en Thalima.',
    charterLead:
      'Southern Wind 110 RS. Ocho huéspedes, cinco de tripulación, verano mediterráneo. Términos MYBA — volvemos con la costa cuando tenemos la semana.',
    theWeek: 'La semana',
    lowSeason: 'Temporada baja',
    highSeason: 'Temporada alta',
    guests: 'Huéspedes',
    crewN: 'Tripulación',
    summer: 'Verano',
    tender: 'Tender',
    weekNote: 'Italia, Cerdeña, el sur de Francia. Términos MYBA. La consulta va al armador.',
    enquire: 'Consulta',
    enquireLead: 'Díganos la semana. El armador la lee y le responde.',
    formOk: 'Debería abrirse el correo con la consulta. Si no, escriba a',
    formNext: 'Continuar',
    formBack: 'Atrás',
    formThanks: 'El equipo le responderá en 24 horas.',
    firstName: 'Nombre *',
    lastName: 'Apellido',
    email: 'Correo *',
    phone: 'Teléfono',
    startDate: 'Fecha de inicio',
    endDate: 'Fecha de fin',
    guestCount: 'Número de huéspedes',
    lengthInterest: 'Eslora de interés',
    location: 'Zona preferida',
    message: 'Su mensaje',
    formNote: 'El armador necesita estos datos para responder. Puede pedir que los olvidemos en cualquier momento.',
    consent: 'Acepto que el armador de Thalima use estos datos para responder a esta consulta de chárter.',
    send: 'Enviar consulta',
    g6: 'Hasta 6 huéspedes',
    g8: '6 – 8 huéspedes',
    gMore: 'Más de 8 huéspedes',
    mediterranean: 'Mediterráneo',
    nEurope: 'Norte de Europa',
    caribbean: 'Caribe',
    asiaPacific: 'Asia-Pacífico',
    other: 'Otro',
    boatLead:
      '33,65 metros. Casco Farr, interior Nauta, construido en Ciudad del Cabo. Ocho huéspedes, cinco de tripulación. Los espacios de huéspedes se rehicieron en Badalona, invierno 2024.',
    deck: 'Cubierta',
    deck1:
      'Cockpit de huéspedes y sunpads juntos. Dodger, bimini, y un toldo de botavara cuando la luz es dura. La tripulación trabaja el cockpit de popa — no cruza a los huéspedes para bajar.',
    deck2: 'La plataforma de baño es el acceso al agua. El Williams está a proa.',
    interior: 'Interior',
    interior1:
      'Armador a proa: cama walk-around, estudio, vestidor, baño. VIP con king, dos literas individuales a popa que se unen. El salón sienta a diez. Tripulación y huéspedes no comparten la bajada.',
    brochureTitle: 'El folleto.',
    brochureLead: 'Noviembre 2025. Cubierta, interior, las líneas. Se abre en PDF.',
    openBrochure: 'Abrir el folleto',
    specsTitle: 'Los números.',
    specsLead: 'La spec de julio para la hoja completa. La lista corta está aquí.',
    openSpec: 'Abrir el PDF spec',
    privacyTitle: 'Lo que guardamos.',
    privacy1:
      'Una consulta de chárter sale de su correo hacia el armador. No guardamos el formulario en este sitio.',
    privacy2:
      'El aviso de cookies escribe un valor en el navegador — aceptar o esencial — para no preguntar otra vez. Sin píxel, sin publicidad, sin rastreo de terceros.',
    privacy3: 'El acceso de tripulación es otra app. Fotos y nombres quedan fuera del sitio público.',
  },
  pt: {
    ...en,
    info: 'Informação',
    brochure: 'Brochura',
    specs: 'Especificações',
    charter: 'Charter',
    contact: 'Contacto',
    language: 'Idioma',
    themeDark: 'Escuro',
    themeLight: 'Claro',
    openMenu: 'Abrir o menu',
    closeMenu: 'Fechar o menu',
    theBoat: 'O barco',
    privacy: 'Privacidade',
    crew: 'Tripulação',
    crewLogin: 'Login da tripulação',
    onThisSite: 'Neste sítio',
    footBlurb: 'Construído na Cidade do Cabo. Navegado no Mediterrâneo.',
    madeForWind: 'Feita para o vento.',
    builtForSea: 'Construída para o mar.',
    sailingYacht: 'Iate à vela',
    capeTown: 'Cidade do Cabo, África do Sul',
    medCruise: 'Cruzeiro no Mediterrâneo',
    explore: 'Explorar',
    specifications: 'Especificações',
    cookieBody:
      'Um único cookie lembra esta escolha. Nada mais é seguido, salvo se aceitar.',
    cookieAccept: 'Aceitar',
    cookieEssential: 'Só essenciais',
    introTitle1: 'Um Southern Wind 110.',
    introTitle2: 'Uma semana calma no Mediterrâneo.',
    introBody:
      'Construído na Cidade do Cabo, desenhado por Farr, vestido por Nauta. Uma lista curta de semanas — Itália, Sardenha, o sul de França — e os mesmos cinco que vivem a bordo. Charter, tripulação, o barco. Sob o mesmo tecto, sem intermediários.',
    servicesEye: 'A bordo',
    servicesTitle: 'O barco, e a semana que leva.',
    svc1Title: 'Uma semana de que se lembra.',
    svc1Body:
      'Diga-nos quando, e onde. Pomos-lhe na Thalima com a tripulação que vive a bordo — Mediterrâneo no verão, o Williams à proa, jantar quando a luz baixa.',
    svc1Cta: 'Começar um charter',
    svc2Title: 'Como está hoje.',
    svc2Body:
      'Convés e interior após o refit 2024. Suíte do armador à proa, salão para dez, o cockpit quando a luz baixa.',
    svc2Cta: 'Ver o barco',
    svc3Title: 'Brochura e especificações.',
    svc3Body:
      'Novembro 2025: convés, interior, as linhas. A spec de julho para os números. Ambas abrem em PDF.',
    svc3Cta: 'Abrir a brochura',
    banner: 'A semana certa muda\na forma como o tempo passa.',
    onboard: 'A bordo',
    selectTitle1: 'Uma pequena seleção, atual.',
    selectTitle2: 'O resto está na brochura.',
    paper: 'Em papel',
    worth: 'Para ler',
    journalLead: 'A brochura, a spec, ou uma semana ainda livre.',
    readMore: 'Ler',
    writeToUs: 'Escrever-nos',
    postBrochure: 'Brochura · nov 2025',
    postBrochureTitle: 'Convés, interior, as linhas.',
    postSpec: 'Especificação',
    postSpecTitle: '33,65 m, Farr, Nauta, Ontario Blue.',
    postCharterTitle: 'Diga-nos a semana. Voltamos com uma costa.',
    ownerSuite: 'Suíte do armador',
    ownerSuiteB: 'À proa, cama walk-around',
    ownerSuiteP: 'Casa de banho · refit 2024',
    underSail: 'À vela',
    underSailB: 'Onze nós quando é amável',
    underSailP: '33,65 m · 8 hóspedes',
    evening: 'Noite',
    eveningB: 'Dez à mesa',
    eveningP: 'Cockpit central',
    lounge: 'Lounge',
    loungeB: 'Depois do inverno em Badalona',
    loungeP: 'Interior',
    saloon: 'Salão',
    saloonB: 'Dez lugares, em silêncio',
    saloonP: 'Nauta · teca',
    contactTitle: 'Escrever, ou ligar.',
    contactLead: 'O charter vai ao armador. Direto — sem broker.',
    telephone: 'Telefone',
    sendEnquiry: 'Enviar um pedido',
    onDeck: 'No convés e abaixo',
    coveAlt: 'Uma cala de granito na Sardenha',
    charterTitle: 'Uma semana na Thalima.',
    charterLead:
      'Southern Wind 110 RS. Oito hóspedes, cinco de tripulação, verão mediterrânico. Termos MYBA — voltamos com a costa quando tivermos a semana.',
    theWeek: 'A semana',
    lowSeason: 'Época baixa',
    highSeason: 'Época alta',
    guests: 'Hóspedes',
    crewN: 'Tripulação',
    summer: 'Verão',
    tender: 'Tender',
    weekNote: 'Itália, Sardenha, o sul de França. Termos MYBA. O pedido vai ao armador.',
    enquire: 'Pedido',
    enquireLead: 'Diga-nos a semana. O armador lê e responde.',
    formOk: 'A sua aplicação de mail deve abrir com o pedido. Se não, escreva para',
    formNext: 'Continuar',
    formBack: 'Voltar',
    formThanks: 'A equipa responde-lhe em 24 horas.',
    firstName: 'Nome *',
    lastName: 'Apelido',
    email: 'Email *',
    phone: 'Telefone',
    startDate: 'Data de início',
    endDate: 'Data de fim',
    guestCount: 'Número de hóspedes',
    lengthInterest: 'Comprimento de interesse',
    location: 'Zona preferida',
    message: 'A sua mensagem',
    formNote: 'O armador precisa destes dados para responder. Pode pedir que os esqueçamos a qualquer momento.',
    consent: 'Aceito que o armador da Thalima use estes dados para responder a este pedido de charter.',
    send: 'Enviar pedido',
    g6: 'Até 6 hóspedes',
    g8: '6 – 8 hóspedes',
    gMore: 'Mais de 8 hóspedes',
    mediterranean: 'Mediterrâneo',
    nEurope: 'Norte da Europa',
    caribbean: 'Caraíbas',
    asiaPacific: 'Ásia-Pacífico',
    other: 'Outro',
    boatLead:
      '33,65 metros. Casco Farr, interior Nauta, construído na Cidade do Cabo. Oito hóspedes, cinco de tripulação. Os espaços de hóspedes foram refeitos em Badalona, inverno 2024.',
    deck: 'Convés',
    deck1:
      'Cockpit de hóspedes e sunpads juntos. Dodger, bimini, e um toldo da retranca quando a luz é dura. A tripulação trabalha o cockpit de ré — não atravessa os hóspedes para descer.',
    deck2: 'A plataforma de banho é o acesso à água. O Williams está à proa.',
    interior: 'Interior',
    interior1:
      'Armador à proa: cama walk-around, escritório, closet, casa de banho. VIP com king, duas camas de solteiro à ré que se juntam. O salão senta dez. Tripulação e hóspedes não partilham a descida.',
    brochureTitle: 'A brochura.',
    brochureLead: 'Novembro 2025. Convés, interior, as linhas. Abre em PDF.',
    openBrochure: 'Abrir a brochura',
    specsTitle: 'Os números.',
    specsLead: 'A spec de julho para a folha completa. A lista curta está aqui.',
    openSpec: 'Abrir o PDF spec',
    privacyTitle: 'O que guardamos.',
    privacy1:
      'Um pedido de charter sai da sua aplicação de mail para o armador. Não guardamos o formulário neste sítio.',
    privacy2:
      'O aviso de cookies escreve um valor no browser — aceitar ou essencial — para não perguntar de novo. Sem pixel, sem publicidade, sem tracker de terceiros.',
    privacy3: 'O login da tripulação é outra app. Fotos e nomes ficam fora do sítio público.',
  },
  ru: {
    ...en,
    info: 'Информация',
    brochure: 'Брошюра',
    specs: 'Спецификация',
    charter: 'Чартер',
    contact: 'Контакты',
    language: 'Язык',
    themeDark: 'Тёмная',
    themeLight: 'Светлая',
    openMenu: 'Открыть меню',
    closeMenu: 'Закрыть меню',
    theBoat: 'Яхта',
    privacy: 'Конфиденциальность',
    crew: 'Экипаж',
    crewLogin: 'Вход экипажа',
    onThisSite: 'На этом сайте',
    footBlurb: 'Построена в Кейптауне. Ходит по Средиземному морю.',
    madeForWind: 'Создана для ветра.',
    builtForSea: 'Построена для моря.',
    sailingYacht: 'Парусная яхта',
    capeTown: 'Кейптаун, Южная Африка',
    medCruise: 'Средиземноморские круизы',
    explore: 'Смотреть',
    specifications: 'Спецификация',
    cookieBody:
      'Один файл cookie запоминает этот выбор. Больше ничего не отслеживается, пока вы не согласитесь.',
    cookieAccept: 'Принять',
    cookieEssential: 'Только необходимые',
    introTitle1: 'Southern Wind 110.',
    introTitle2: 'Тихая неделя на Средиземном море.',
    introBody:
      'Построена в Кейптауне, корпус Farr, интерьер Nauta. Короткий список недель — Италия, Сардиния, юг Франции — и те же пятеро, кто живёт на борту. Чартер, экипаж, яхта. Без посредников.',
    servicesEye: 'На борту',
    servicesTitle: 'Яхта и неделя, которую вы берёте.',
    svc1Title: 'Неделя, которую помнят.',
    svc1Body:
      'Скажите когда и где. Мы ставим вас на Thalima с экипажем, который живёт на борту — Средиземное море летом, Williams на баке, ужин, когда гаснет свет.',
    svc1Cta: 'Начать чартер',
    svc2Title: 'Какая она сегодня.',
    svc2Body:
      'Палуба и интерьер после рефита 2024. Каюта владельца в носу, салон на десять, кокпит, когда гаснет свет.',
    svc2Cta: 'Смотреть яхту',
    svc3Title: 'Брошюра и спецификация.',
    svc3Body:
      'Ноябрь 2025: палуба, интерьер, линии. Июльская спецификация для цифр. Оба открываются как PDF.',
    svc3Cta: 'Открыть брошюру',
    banner: 'Нужная неделя меняет\nто, как идёт время.',
    onboard: 'На борту',
    selectTitle1: 'Небольшая подборка, актуальная сегодня.',
    selectTitle2: 'Остальное — в брошюре.',
    paper: 'На бумаге',
    worth: 'Стоит прочитать',
    journalLead: 'Брошюра, спецификация или ещё свободная неделя.',
    readMore: 'Читать',
    writeToUs: 'Написать',
    postBrochure: 'Брошюра · ноя 2025',
    postBrochureTitle: 'Палуба, интерьер, линии.',
    postSpec: 'Спецификация',
    postSpecTitle: '33,65 м, Farr, Nauta, Ontario Blue.',
    postCharterTitle: 'Назовите неделю. Мы вернёмся с побережьем.',
    ownerSuite: 'Каюта владельца',
    ownerSuiteB: 'В носу, кровать walk-around',
    ownerSuiteP: 'Санузел · рефит 2024',
    underSail: 'Под парусом',
    underSailB: 'Одиннадцать узлов, когда море доброе',
    underSailP: '33,65 м · 8 гостей',
    evening: 'Вечер',
    eveningB: 'Десять за столом',
    eveningP: 'Центральный кокпит',
    lounge: 'Гостиная',
    loungeB: 'После зимы в Бадалоне',
    loungeP: 'Интерьер',
    saloon: 'Салон',
    saloonB: 'Десять мест, тихо',
    saloonP: 'Nauta · тик',
    contactTitle: 'Написать или позвонить.',
    contactLead: 'Чартер идёт владельцу. Напрямую — без брокера.',
    telephone: 'Телефон',
    sendEnquiry: 'Отправить запрос',
    onDeck: 'На палубе и внизу',
    coveAlt: 'Гранитная бухта на Сардинии',
    charterTitle: 'Неделя на Thalima.',
    charterLead:
      'Southern Wind 110 RS. Восемь гостей, пять экипажа, средиземноморское лето. Условия MYBA — мы вернёмся с побережьем, когда будет неделя.',
    theWeek: 'Неделя',
    lowSeason: 'Низкий сезон',
    highSeason: 'Высокий сезон',
    guests: 'Гости',
    crewN: 'Экипаж',
    summer: 'Лето',
    tender: 'Тендер',
    weekNote: 'Италия, Сардиния, юг Франции. Условия MYBA. Запрос идёт владельцу.',
    enquire: 'Запрос',
    enquireLead: 'Назовите неделю. Владелец читает и отвечает.',
    formOk: 'Почтовое приложение должно открыться с запросом. Если нет, напишите',
    formNext: 'Далее',
    formBack: 'Назад',
    formThanks: 'Команда ответит в течение 24 часов.',
    firstName: 'Имя *',
    lastName: 'Фамилия',
    email: 'Эл. почта *',
    phone: 'Телефон',
    startDate: 'Дата начала',
    endDate: 'Дата окончания',
    guestCount: 'Число гостей',
    lengthInterest: 'Интересующая длина',
    location: 'Предпочтительный район',
    message: 'Ваше сообщение',
    formNote: 'Владельцу нужны эти данные, чтобы ответить. Их можно попросить забыть в любой момент.',
    consent: 'Я согласен, что владелец Thalima использует эти данные для ответа на запрос чартера.',
    send: 'Отправить запрос',
    g6: 'До 6 гостей',
    g8: '6 – 8 гостей',
    gMore: 'Более 8 гостей',
    mediterranean: 'Средиземное море',
    nEurope: 'Северная Европа',
    caribbean: 'Карибы',
    asiaPacific: 'Азиатско-Тихоокеанский регион',
    other: 'Другое',
    boatLead:
      '33,65 метра. Корпус Farr, интерьер Nauta, построена в Кейптауне. Восемь гостей, пять экипажа. Гостевые помещения переделаны в Бадалоне зимой 2024.',
    deck: 'Палуба',
    deck1:
      'Гостевой кокпит и санпады рядом. Доджер, бимини и тент гика, когда свет жёсткий. Экипаж работает в кормовом кокпите — не проходит через гостей, чтобы спуститься.',
    deck2: 'Купальная платформа — вход в воду. Williams стоит на баке.',
    interior: 'Интерьер',
    interior1:
      'Владелец в носу: кровать walk-around, кабинет, гардероб, санузел. VIP с king, две односпальные в корме, которые можно соединить. Салон на десять. Экипаж и гости не делят трап.',
    brochureTitle: 'Брошюра.',
    brochureLead: 'Ноябрь 2025. Палуба, интерьер, линии. Открывается как PDF.',
    openBrochure: 'Открыть брошюру',
    specsTitle: 'Цифры.',
    specsLead: 'Июльская спецификация — полный лист. Краткий список здесь.',
    openSpec: 'Открыть PDF спецификации',
    privacyTitle: 'Что мы храним.',
    privacy1:
      'Запрос чартера уходит из вашего почтового приложения владельцу. Мы не храним форму на этом сайте.',
    privacy2:
      'Баннер cookie пишет одно значение в браузер — принять или необходимое — чтобы не спрашивать снова. Нет аналитики, рекламы и сторонних трекеров.',
    privacy3: 'Вход экипажа — отдельное приложение. Фото и имена экипажа остаются вне публичного сайта.',
  },
  zh: {
    ...en,
    info: '信息',
    brochure: '画册',
    specs: '参数',
    charter: '包船',
    contact: '联系',
    language: '语言',
    themeDark: '深色',
    themeLight: '浅色',
    openMenu: '打开菜单',
    closeMenu: '关闭菜单',
    theBoat: '游艇',
    privacy: '隐私',
    crew: '船员',
    crewLogin: '船员登录',
    onThisSite: '本站',
    footBlurb: '建于开普敦。航行于地中海。',
    madeForWind: '为风而生。',
    builtForSea: '为海而建。',
    sailingYacht: '帆船游艇',
    capeTown: '南非开普敦',
    medCruise: '地中海巡航',
    explore: '探索',
    specifications: '规格',
    cookieBody: '我们只用一枚 cookie 记住此选择。除非您同意，否则不做其他追踪。',
    cookieAccept: '接受',
    cookieEssential: '仅必要',
    introTitle1: '一艘 Southern Wind 110。',
    introTitle2: '地中海安静的一周。',
    introBody:
      '开普敦建造，Farr 船体，Nauta 内装。少量档期——意大利、撒丁、法国南部——以及长住船上的五名船员。包船、船员、游艇。同一屋檐下，没有中间人。',
    servicesEye: '船上',
    servicesTitle: '这艘游艇，以及您带走的一周。',
    svc1Title: '真正记得住的一周。',
    svc1Body:
      '告诉我们时间和地点。我们把您送上 Thalima，与住在船上的船员一起——夏日地中海，前甲板的 Williams，光线落下时的晚餐。',
    svc1Cta: '开始包船',
    svc2Title: '今日之状。',
    svc2Body: '2024 翻新后的甲板与内装。船主套房在前，客厅可坐十人，光线落下时的驾驶舱。',
    svc2Cta: '看船',
    svc3Title: '画册与规格。',
    svc3Body: '2025 年 11 月：甲板、内装、线条。七月规格看数字。均为 PDF。',
    svc3Cta: '打开画册',
    banner: '对的一周，\n会改变时间流过的方式。',
    onboard: '船上',
    selectTitle1: '一小部分，今天仍是这样。',
    selectTitle2: '其余在画册里。',
    paper: '纸上',
    worth: '值得一读',
    journalLead: '画册、规格，或仍空着的一周。',
    readMore: '阅读',
    writeToUs: '写信',
    postBrochure: '画册 · 2025.11',
    postBrochureTitle: '甲板、内装、线条。',
    postSpec: '规格',
    postSpecTitle: '33.65 米，Farr，Nauta，Ontario Blue。',
    postCharterTitle: '告诉我们那一周。我们带着海岸回来。',
    ownerSuite: '船主套房',
    ownerSuiteB: '前部，环绕式床铺',
    ownerSuiteP: '独立卫浴 · 2024 翻新',
    underSail: '扬帆',
    underSailB: '风顺时十一节',
    underSailP: '33.65 米 · 8 位客人',
    evening: '傍晚',
    eveningB: '十人围桌',
    eveningP: '中央驾驶舱',
    lounge: '起居',
    loungeB: '巴达洛纳之冬以后',
    loungeP: '内装',
    saloon: '客厅',
    saloonB: '十人静坐',
    saloonP: 'Nauta · 柚木',
    contactTitle: '写信，或来电。',
    contactLead: '包船直达船主。没有经纪人。',
    telephone: '电话',
    sendEnquiry: '发送询盘',
    onDeck: '甲板与舱内',
    coveAlt: '撒丁岛花岗岩海湾',
    charterTitle: '在 Thalima 的一周。',
    charterLead:
      'Southern Wind 110 RS。八位客人，五名船员，地中海之夏。MYBA 条款——有了档期，我们带着海岸回来。',
    theWeek: '这一周',
    lowSeason: '淡季',
    highSeason: '旺季',
    guests: '客人',
    crewN: '船员',
    summer: '夏季',
    tender: '艇',
    weekNote: '意大利、撒丁、法国南部。MYBA 条款。询盘发给船主。',
    enquire: '询盘',
    enquireLead: '告诉我们那一周。船主会读，并回复您。',
    formOk: '邮件应用应会打开询盘。若没有，请写信至',
    formNext: '继续',
    formBack: '返回',
    formThanks: '团队将在 24 小时内回复您。',
    firstName: '名 *',
    lastName: '姓',
    email: '电子邮箱 *',
    phone: '电话',
    startDate: '起始日期',
    endDate: '结束日期',
    guestCount: '客人数',
    lengthInterest: '感兴趣的船长',
    location: '偏好海域',
    message: '留言',
    formNote: '船主需要这些信息才能回复。您可随时要求我们删除。',
    consent: '我同意 Thalima 船主使用这些信息回复本次包船询盘。',
    send: '发送询盘',
    g6: '最多 6 位客人',
    g8: '6 – 8 位客人',
    gMore: '超过 8 位客人',
    mediterranean: '地中海',
    nEurope: '北欧',
    caribbean: '加勒比',
    asiaPacific: '亚太',
    other: '其他',
    boatLead:
      '33.65 米。Farr 船体，Nauta 内装，开普敦建造。八位客人，五名船员。客人区域于 2024 年冬在巴达洛纳翻新。',
    deck: '甲板',
    deck1:
      '客人驾驶舱与日光垫相连。遮浪、遮阳，光线刺眼时还有主桁篷。船员在尾驾驶舱工作——下舱不必穿过客人。',
    deck2: '泳台是入水处。Williams 停在前甲板。',
    interior: '内装',
    interior1:
      '船主在前：环绕式床、书房、步入式衣帽间、独立卫浴。VIP 为大床，尾部两张单人床可拼。客厅可坐十人。船员与客人不同梯道。',
    brochureTitle: '画册。',
    brochureLead: '2025 年 11 月。甲板、内装、线条。以 PDF 打开。',
    openBrochure: '打开画册',
    specsTitle: '数字。',
    specsLead: '七月规格是完整表。短名单在此。',
    openSpec: '打开规格 PDF',
    privacyTitle: '我们保留什么。',
    privacy1: '包船询盘从您的邮件应用发给船主。我们不在本站存储表单。',
    privacy2: 'Cookie 横幅在浏览器中写入一个值——接受或仅必要——以免再问。没有分析像素、广告网络或第三方追踪。',
    privacy3: '船员登录是另一套应用。船员照片与姓名不出现在公开站点。',
  },
  ja: {
    ...en,
    info: '情報',
    brochure: 'パンフレット',
    specs: 'スペック',
    charter: 'チャーター',
    contact: '連絡',
    language: '言語',
    themeDark: 'ダーク',
    themeLight: 'ライト',
    openMenu: 'メニューを開く',
    closeMenu: 'メニューを閉じる',
    theBoat: '艇',
    privacy: 'プライバシー',
    crew: 'クルー',
    crewLogin: 'クルーログイン',
    onThisSite: 'このサイト',
    footBlurb: 'ケープタウンで建造。地中海を走る。',
    madeForWind: '風のために。',
    builtForSea: '海のために。',
    sailingYacht: 'セーリングヨット',
    capeTown: 'ケープタウン、南アフリカ',
    medCruise: '地中海クルージング',
    explore: '見る',
    specifications: '仕様',
    cookieBody: 'この選択を覚えるクッキーは一つだけです。同意しない限り、他は追跡しません。',
    cookieAccept: '同意する',
    cookieEssential: '必須のみ',
    introTitle1: 'Southern Wind 110。',
    introTitle2: '地中海の静かな一週間。',
    introBody:
      'ケープタウン建造、Farr の船体、Nauta の内装。短い週のリスト——イタリア、サルデーニャ、南仏——と、船上で暮らす同じ五人。チャーター、クルー、艇。仲介なし、ひとつの屋根の下。',
    servicesEye: '船上',
    servicesTitle: '艇と、乗る一週間。',
    svc1Title: '覚えている一週間。',
    svc1Body:
      'いつ、どこかを教えてください。船上で暮らすクルーとともに Thalima へ——夏の地中海、フォアデッキの Williams、光が落ちるときの夕食。',
    svc1Cta: 'チャーターを始める',
    svc2Title: '今日の姿。',
    svc2Body: '2024年改装後のデッキと内装。前方のオーナースイート、十人のサロン、光が落ちるときのコックピット。',
    svc2Cta: '艇を見る',
    svc3Title: 'パンフレットとスペック。',
    svc3Body: '2025年11月：デッキ、内装、ライン。数字は七月のスペック。どちらもPDF。',
    svc3Cta: 'パンフレットを開く',
    banner: '合う一週間は、\n時間の流れ方を変える。',
    onboard: '船上',
    selectTitle1: '今日の小さな選定。',
    selectTitle2: '残りはパンフレットの中に。',
    paper: '紙の上',
    worth: '読む価値',
    journalLead: 'パンフレット、スペック、またはまだ空いている一週間。',
    readMore: '読む',
    writeToUs: '書く',
    postBrochure: 'パンフレット · 2025.11',
    postBrochureTitle: 'デッキ、内装、ライン。',
    postSpec: '仕様',
    postSpecTitle: '33.65 m、Farr、Nauta、Ontario Blue。',
    postCharterTitle: '週を教えてください。海岸を持って戻ります。',
    ownerSuite: 'オーナーズスイート',
    ownerSuiteB: '前方、ウォークアラウンドベッド',
    ownerSuiteP: '専用浴室 · 2024 改装',
    underSail: 'セール中',
    underSailB: '穏やかなときの十一ノット',
    underSailP: '33.65 m · ゲスト8名',
    evening: '夕方',
    eveningB: 'テーブルを囲む十人',
    eveningP: 'センターコックピット',
    lounge: 'ラウンジ',
    loungeB: 'バダロナの冬のあと',
    loungeP: '内装',
    saloon: 'サロン',
    saloonB: '十人が静かに座る',
    saloonP: 'Nauta · チーク',
    contactTitle: '書くか、電話を。',
    contactLead: 'チャーターはオーナーへ。直接——ブローカーなし。',
    telephone: '電話',
    sendEnquiry: '問い合わせを送る',
    onDeck: 'デッキと下',
    coveAlt: 'サルデーニャの花崗岩の入り江',
    charterTitle: 'Thalima の一週間。',
    charterLead:
      'Southern Wind 110 RS。ゲスト八名、クルー五名、地中海の夏。MYBA 条件——週が決まれば、海岸を持って戻ります。',
    theWeek: 'その週',
    lowSeason: 'ローシーズン',
    highSeason: 'ハイシーズン',
    guests: 'ゲスト',
    crewN: 'クルー',
    summer: '夏',
    tender: 'テンダー',
    weekNote: 'イタリア、サルデーニャ、南仏。MYBA 条件。問い合わせはオーナーへ。',
    enquire: '問い合わせ',
    enquireLead: '週を教えてください。オーナーが読み、返信します。',
    formOk: 'メールアプリが問い合わせとともに開くはずです。開かない場合は次へ書いてください',
    formNext: '続ける',
    formBack: '戻る',
    formThanks: '24時間以内にご連絡します。',
    firstName: '名 *',
    lastName: '姓',
    email: 'メール *',
    phone: '電話',
    startDate: '開始日',
    endDate: '終了日',
    guestCount: 'ゲスト数',
    lengthInterest: '希望全長',
    location: '希望海域',
    message: 'メッセージ',
    formNote: 'オーナーが返信するにはこれらの情報が必要です。いつでも削除を求められます。',
    consent: 'Thalima のオーナーがこのチャーター問い合わせへの返信にこれらの情報を使うことに同意します。',
    send: '問い合わせを送る',
    g6: 'ゲスト6名まで',
    g8: 'ゲスト 6 – 8 名',
    gMore: 'ゲスト8名超',
    mediterranean: '地中海',
    nEurope: '北欧',
    caribbean: 'カリブ',
    asiaPacific: 'アジア太平洋',
    other: 'その他',
    boatLead:
      '33.65 メートル。Farr 船体、Nauta 内装、ケープタウン建造。ゲスト八名、クルー五名。ゲスト空間は 2024 年冬、バダロナでやり直しました。',
    deck: 'デッキ',
    deck1:
      'ゲストコックピットとサンパッドは一体。ドジャー、ビミニ、光が強いときのブームオーニング。クルーはアフトコックピットで働く——下へ行くためにゲストを横切らない。',
    deck2: 'スイムプラットフォームが水への入り口。Williams はフォアデッキにあります。',
    interior: '内装',
    interior1:
      '前方オーナー：ウォークアラウンドベッド、書斎、ウォークイン、専用浴室。VIP はキング、後方のツインはダブルにできます。サロンは十人。クルーとゲストは同じ階段を使いません。',
    brochureTitle: 'パンフレット。',
    brochureLead: '2025年11月。デッキ、内装、ライン。PDF で開きます。',
    openBrochure: 'パンフレットを開く',
    specsTitle: '数字。',
    specsLead: '七月のスペックが全表。短いリストはここにあります。',
    openSpec: 'スペック PDF を開く',
    privacyTitle: '私たちが残すもの。',
    privacy1: 'チャーター問い合わせはメールアプリからオーナーへ送られます。このサイトにフォームは保存しません。',
    privacy2: 'クッキーバナーはブラウザに一つの値——同意または必須——を書き、再表示しません。分析ピクセル、広告、第三者トラッカーはありません。',
    privacy3: 'クルーのログインは別アプリです。クルーの写真と名前は公開サイトに出しません。',
  },
}

export const LANG_KEY = 'thalima.lp.lang'
export const THEME_KEY = 'thalima.lp.theme'

export function readLang(): Lang {
  try {
    const raw = localStorage.getItem(LANG_KEY)
    if (raw && LANGS.some((l) => l.id === raw)) return raw as Lang
  } catch {
    /* ignore */
  }
  return 'en'
}

export function readNight(): boolean {
  try {
    return localStorage.getItem(THEME_KEY) !== 'light'
  } catch {
    return true
  }
}

export function writeTheme(theme: 'light' | 'dark') {
  try {
    localStorage.setItem(THEME_KEY, theme)
  } catch {
    /* private */
  }
}

export function applyHtmlTheme(theme: 'light' | 'dark') {
  const html = document.documentElement
  html.dataset.theme = theme
  html.style.colorScheme = theme
}
